meta_name: "LeagueBox"
meta_title: "LeagueBox Â· The path to competitive social tennis"
meta_description: "Join your club's box league to play competitive and social tennis in your local club"
meta_image: box_league_racket.png
meta_site_name: "LeagueBox"
